name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential sdcc 

    - name: Build
      run: |
        sdcc -c -mz80 --std-c99 --opt-code-size --fsigned-char --model-small --nogcse --noinvariant --noinduction --nojtbound --noloopreverse --nolabelopt --no-peep --no-reg-params --no-peep-return --nooverlay


    



