name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install build-essential sdcc 

    - name: Blink example
      working-directory: Software/examples/Blink
      run: make all
    
    - name: ADC example
      working-directory: Software/examples/ADC
      run: make all
      
